### ISSUE TITLE
other user cant stake

### ISSUE THREAD

**Issue by mark101010x** [net2devcrypto/nftstaking#5]
I transferred the NFT using opensea to other account (a common way to send NFT) and tried to stake not working
i also tried to mint NFT on another account and stake not working
staking only works on the contract deployer.

**Comment by net2devcrypto** [comment]
Hi, I saw what the issue is. Remember on the video when I've approved with my contract owner wallet, the NFT staking smartcontract to interact with the NFT Collection Smart Contract? Im not approving it to have full control of all NFT's moved, Im approving the NFT Staking smart contract to manage the NFTs belonging to my wallet using the SetApprovedForAll under the NFT Collection Smart Contract. This is to allow the NFT Owner full control of the NFTs on the wallet. If this wasn't implemented, can you imagine any smart contract owner removing the NFT's from your wallet and staking them without your consent? This is why it set this way so you and only you can approve the staking smart contract to transfer the NFTs from your wallet by calling the NFT collection smart contract :)  Every NFT holder that would like to stake their NFT's needs to grant permission to the staking smartcontract to execute the safetransferfrom function on their behalf. This is easy. On the Web3 dApp we can code the "Stake" button to first grant by the NFT owner's wallet approval to the staking smart contract to move the NFT's from the wallet to the vault. Im making a short video regarding your concern and a demo. Thanks!!

**Comment by mark101010x** [comment]
Okey thank you i cant wait to see your vids.
